In [1]:
import numpy as np
np.arange(10).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a = np.arange(10)
c = np.reshape(a, (-2, 1))
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [4]:
a.shape

(10,)

In [5]:
a.shape = (2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [6]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
c

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
p = c.flatten()
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.newaxis?

In [11]:
data = np.arange(0, 5)
c = data[:, np.newaxis]
c

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [12]:
data

array([0, 1, 2, 3, 4])

In [13]:
a = np.arange(9).reshape((3,3))
b = np.arange(12).reshape((3,4))
c = np.arange(15).reshape((3,5))

In [14]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
np.hstack((a, b))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [18]:
np.stack?

In [19]:
np.stack((a,b))

ValueError: all input arrays must have the same shape

In [22]:
np.concatenate((a, b), axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [23]:
b.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [24]:
np.vstack((a, b.T))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [25]:
a = np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [26]:
np.split(a, 2, axis=1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [30]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
b

array([[7, 8, 9]])

In [31]:
r = np.append(a, b, axis=0)

In [32]:
r

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

np.insert, np.delete, np.flatten, np.append

In [36]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
b = a + 10  #a - 10, a / 10
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [38]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
a + b

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [41]:
a - b

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [42]:
a / b

array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

In [43]:
a * b

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [44]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [46]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
m = np.arange(5)
m

array([0, 1, 2, 3, 4])

In [48]:
a + m

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [49]:
n = np.arange(1, 3).reshape((-1, 1))
n

array([[1],
       [2]])

In [50]:
a + n

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [52]:
np.array([6, 3, 4]) > np.array([9, 5, 1])

array([False, False,  True])

In [ ]:
a = np.array([3, 6, 9])
b = np.array([4, 5,8])
a < b and a > b

np.logical_and, np.logic_or, logical_not, logical_xor

In [53]:
alpha = np.linspace(-1, 1, 11)
y = np.sin(np.pi * alpha)
np.round(y, decimals = 2)

array([-0.  , -0.59, -0.95, -0.95, -0.59,  0.  ,  0.59,  0.95,  0.95,
        0.59,  0.  ])

In [54]:
def bmi(h, w):
    bmi_index = w / h ** 2
    if bmi_index > 18 and bmi_index < 25:
        return 0
    elif bmi_index <= 18:
        return -1
    else:
        return 1

bmi(1.7, 100)

1

In [55]:
h = (2.2 - 1.4) * np.random.random_sample((10,)) + 1.4
h = np.round(h, 2)
w = (96 - 30)* np.random.random_sample((10,)) + 30
w = np.round(w, 2)

In [56]:
bmi(h, w)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [57]:
bmi_ufunc = np.frompyfunc(bmi, 2, 1)

In [58]:
bmi_ufunc(h, w)

array([-1, 1, 0, -1, -1, -1, 0, 1, -1, -1], dtype=object)

In [59]:
pow_ufunc = np.frompyfunc(pow, 2, 1)
a = np.arange(10)
pow_ufunc(a, a)

array([1, 1, 4, 27, 256, 3125, 46656, 823543, 16777216, 387420489],
      dtype=object)

In [60]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.vectorize

In [61]:
mu, sigma = 0.0, 1.0
g = np.random.normal(loc=mu, scale=sigma, size=1000)
#np.random.randn(1000)

In [62]:
g1 = np.random.randn(1000)

In [63]:
g = (g - g.min()) / 10
phy = np.round(((100.1 - 20) * g + 20), 1)
g1 = (g1 - g1.min()) / 10
mat = np.round(((100.1 - 20) * g1 + 20), 1)

In [64]:
phy

array([46.2, 55. , 33.8, 56. , 41.9, 33.3, 45.3, 46. , 44.8, 31.8, 42.9,
       38. , 33.4, 30.9, 41.6, 46.7, 43.6, 37.7, 40.4, 53.1, 50.9, 40.9,
       46.5, 42.3, 37.4, 51. , 36.3, 43.3, 57.8, 30.7, 52.3, 39.5, 39.6,
       37.6, 43.6, 53.3, 51.1, 49.8, 45.4, 34.6, 38.9, 40.1, 54.1, 49.6,
       42. , 55.2, 48.7, 28.4, 57. , 35.5, 47.8, 43.3, 39.2, 50.8, 44.7,
       60.7, 30.6, 59. , 52.3, 38.3, 41.8, 59.1, 39.3, 33.6, 46.3, 47.6,
       40.6, 35.9, 51.5, 39.7, 41.1, 49.6, 48.4, 39.5, 50.3, 33.6, 54.3,
       55. , 39.3, 57.4, 52. , 42.7, 45.3, 47.4, 46.4, 42.9, 33.3, 47.2,
       47.9, 73.6, 52.2, 53.7, 46.1, 46.5, 46.4, 66.1, 41.3, 40.3, 47.3,
       54.5, 52.2, 47.1, 39.8, 50.9, 44.4, 33.3, 28. , 38.1, 51.4, 36.6,
       32.8, 30.3, 41.8, 41.5, 35.7, 42.3, 49.2, 37.8, 29.4, 45.8, 32.3,
       31.8, 57.1, 40.4, 43.6, 45.9, 43.1, 30.2, 54.3, 39. , 53.6, 48.8,
       38. , 47.6, 43.1, 40.4, 27.8, 48.2, 55. , 31.7, 32.5, 29.9, 50.9,
       23. , 35.5, 39.2, 49.8, 46.1, 52.3, 43.3, 40

In [65]:
mat

array([41.3, 44. , 44.6, 36.9, 57.9, 74.3, 51.4, 49.9, 66.5, 31. , 51.2,
       44.5, 54.3, 38.3, 45.6, 54.6, 60.8, 48. , 54.5, 39. , 43.6, 46.2,
       48.5, 35.6, 40.4, 54.7, 63.9, 46.3, 43.2, 49.6, 51.9, 54.9, 62.8,
       53. , 53.7, 55.4, 42.1, 49. , 63.2, 68. , 44.1, 45.9, 53.1, 37.4,
       52.7, 37.9, 43. , 45.4, 48.3, 50.4, 53.7, 72. , 54. , 34. , 54.1,
       49.9, 35.9, 37.7, 47.9, 52.4, 48.4, 43.3, 32. , 37.9, 36.5, 55.5,
       29.8, 36.7, 51.2, 48.9, 24.7, 46.8, 46.6, 50.6, 41.9, 47.4, 52.3,
       48.6, 38.5, 39.4, 49.1, 54.5, 47.4, 53.2, 47.5, 50.2, 47. , 54.6,
       41.7, 55.4, 41.2, 47.1, 54.2, 54.3, 58.3, 37.8, 44.3, 53.9, 49.6,
       46.4, 37.6, 53.8, 43. , 38.9, 47.3, 47.3, 49.3, 39.9, 54.6, 61.9,
       57.7, 49.4, 37.6, 64.3, 55.9, 63.4, 46.6, 51.1, 31.7, 55.6, 60.9,
       50. , 43.3, 47. , 51.4, 50.1, 46.8, 36.8, 35.9, 35.9, 52.1, 52.5,
       43.8, 51.6, 47. , 52.8, 50.9, 32.3, 48.9, 43.4, 48.9, 48.5, 54.5,
       60.5, 43.6, 47.3, 31.1, 38.1, 59. , 53.9, 37

In [66]:
np.mean(phy)

44.4496

In [67]:
np.std(phy)

7.977001933057306

In [68]:
np.min(phy), np.max(phy)

(20.0, 74.8)

In [69]:
np.percentile(phy, 80)

51.1

In [70]:
np.median(phy)

44.2

In [71]:
marks = np.vstack((phy, mat))

In [72]:
np.mean(marks,axis=1)

array([44.4496, 48.1981])

In [73]:
np.mean(marks)

46.32385000000001

In [74]:
phy[phy>np.mean(phy)]

array([46.2, 55. , 56. , 45.3, 46. , 44.8, 46.7, 53.1, 50.9, 46.5, 51. ,
       57.8, 52.3, 53.3, 51.1, 49.8, 45.4, 54.1, 49.6, 55.2, 48.7, 57. ,
       47.8, 50.8, 44.7, 60.7, 59. , 52.3, 59.1, 46.3, 47.6, 51.5, 49.6,
       48.4, 50.3, 54.3, 55. , 57.4, 52. , 45.3, 47.4, 46.4, 47.2, 47.9,
       73.6, 52.2, 53.7, 46.1, 46.5, 46.4, 66.1, 47.3, 54.5, 52.2, 47.1,
       50.9, 51.4, 49.2, 45.8, 57.1, 45.9, 54.3, 53.6, 48.8, 47.6, 48.2,
       55. , 50.9, 49.8, 46.1, 52.3, 52.1, 49.7, 45.3, 52.7, 46.5, 46.8,
       45.7, 48.5, 48.7, 46.5, 44.6, 45.7, 47.1, 47.7, 44.7, 51.8, 54.2,
       51.1, 51.5, 58.5, 46.3, 57. , 50.5, 48.1, 51.4, 45.6, 45.3, 53.2,
       45.5, 44.9, 48.2, 49.2, 47.3, 49.4, 57.9, 59.4, 49.3, 51. , 59.2,
       51.8, 51.2, 60.6, 46.8, 51.4, 48.7, 50.9, 53.5, 51.5, 46.6, 48.2,
       49.9, 51.8, 54. , 57.2, 52.3, 52. , 56.3, 50.4, 50.3, 52.6, 52.5,
       53. , 49.3, 44.5, 55.3, 48.3, 53.2, 44.7, 47.3, 56.4, 44.8, 58.1,
       45.9, 48.6, 61.5, 45.9, 57.7, 48.1, 47.9, 65

In [75]:
np.where(phy>mat,1,-1)

array([ 1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1,  1,  1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1, -1, -1, -1,
       -1, -1,  1,  1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1, -1, -1,
       -1, -1,  1, -1,  1, -1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1, -1,
        1, -1,  1,  1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1, -1, -1, -1,
       -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1, -1, -1,  1,  1, -1,
       -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1, -1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1, -1,  1,  1,  1, -1, -1, -1, -1, -1,
       -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1,  1, -1,
       -1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1,
       -1,  1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1, -1,  1, -1, -1, -1,
       -1, -1,  1, -1, -1,  1, -1, -1,  1,  1, -1, -1,  1,  1, -1, -1, -1,
       -1, -1,  1, -1, -1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1, -1,  1,
       -1,  1, -1,  1,  1

In [76]:
A = np.mat([1,2,3])
A

matrix([[1, 2, 3]])

In [77]:
B = np.mat('1 2 3; 4 5 6;7 8 9')
B

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
np.mat(np.eye(2))

matrix([[1., 0.],
        [0., 1.]])

In [80]:
a = np.arange(1, 10).reshape(3,3)
b = np.array([[1,0,1],[0,1,1],[1,1,0]])

In [81]:
a * b

array([[1, 0, 3],
       [0, 5, 6],
       [7, 8, 0]])

In [82]:
A = np.mat(a)
B = np.mat(b)
A * B

matrix([[ 4,  5,  3],
        [10, 11,  9],
        [16, 17, 15]])

In [83]:
np.dot(a,b)

array([[ 4,  5,  3],
       [10, 11,  9],
       [16, 17, 15]])

标量积 np.dot
内积 np.inner

In [84]:
np.inner?

In [85]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])
np.dot(c,d)

array([[19, 22],
       [43, 50]])

In [86]:
np.inner(c, d)

array([[17, 23],
       [39, 53]])

矢量积np.cross
张量积np.tensordot

In [88]:
a = np.array([1, -2, 1])
p = np.poly1d(a)

In [89]:
p(1)

0

In [91]:
a = np.array([1,3,1])
g = np.poly1d(a)
f = lambda x: g(x-1)
f(0.0)

-1.0

In [92]:
np.poly1d?

In [93]:
print(f)

<function <lambda> at 0x10eaa5d08>


In [94]:
print(g)

   2
1 x + 3 x + 1


np.linalg

In [95]:
import pandas as pd

In [96]:
a

array([1, 3, 1])

In [97]:
s = pd.Series(a, index=['a', 'b', 'c'])
s

a    1
b    3
c    1
dtype: int64

In [98]:
a[0]

1

In [99]:
s["a"]

1

In [102]:
s1 = pd.Series([1,23,4], index=[1,2,3])

In [103]:
s1

1     1
2    23
3     4
dtype: int64

In [104]:
s1[1]

1

In [105]:
pd.Series({"a":11, "b":88, "c":99})

a    11
b    88
c    99
dtype: int64

In [106]:
s

a    1
b    3
c    1
dtype: int64

In [108]:
s.name = "hello"

In [109]:
s

a    1
b    3
c    1
Name: hello, dtype: int64

In [110]:
s.index

Index(['a', 'b', 'c'], dtype='object')

In [111]:
s.index.name = "world"

In [112]:
s

world
a    1
b    3
c    1
Name: hello, dtype: int64

In [113]:
df = pd.DataFrame([[100, 200, 300],[101,201, 301], [102,202,302]])

In [114]:
df

0    1    2
0  100  200  300
1  101  201  301
2  102  202  302

In [115]:
df.index = ['zhang','li','wang']

In [116]:
df

0    1    2
zhang  100  200  300
li     101  201  301
wang   102  202  302

In [117]:
df.columns = ['english', 'math', 'phy']

In [119]:
df

english  math  phy
zhang      100   200  300
li         101   201  301
wang       102   202  302

In [120]:
pd.DataFrame?

In [123]:
df.index.name = "xingming"
df.columns.name = "xueke"
df

xueke     english  math  phy
xingming                    
zhang         100   200  300
li            101   201  301
wang          102   202  302

In [124]:
pd.DataFrame({"english": [100, 89, 20], "chinese":[30, 100, 45]})

english  chinese
0      100       30
1       89      100
2       20       45

In [125]:
s

world
a    1
b    3
c    1
Name: hello, dtype: int64

In [126]:
s.index

Index(['a', 'b', 'c'], dtype='object', name='world')

In [127]:
s.index[0]

'a'

In [128]:
df.index

Index(['zhang', 'li', 'wang'], dtype='object', name='xingming')

In [129]:
df

xueke     english  math  phy
xingming                    
zhang         100   200  300
li            101   201  301
wang          102   202  302

In [130]:
df.columns

Index(['english', 'math', 'phy'], dtype='object', name='xueke')

In [131]:
city_index=[("china","beijing"),("china","shanghai"),("usa",'chicago')]

In [132]:
city = pd.MultiIndex.from_tuples(city_index)
city

MultiIndex(levels=[['china', 'usa'], ['beijing', 'chicago', 'shanghai']],
           labels=[[0, 0, 1], [0, 2, 1]])

In [135]:
gdp_index = [("shanghai", 2015), ("shanghai", 2016), ("beijing",2015),("beijing", 2016)]
gdp_mind = pd.MultiIndex.from_tuples(gdp_index)
gdp = pd.Series([25300, 27466, 23000, 24899], index=gdp_mind)
gdp

shanghai  2015    25300
          2016    27466
beijing   2015    23000
          2016    24899
dtype: int64

In [136]:
gdp['shanghai']

2015    25300
2016    27466
dtype: int64

In [137]:
gdp.iloc[1]

27466

In [140]:
s.loc[:1]

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <class 'int'>

In [143]:
s.iloc[1:2]

world
b    3
Name: hello, dtype: int64

README.md         first_program.py  guess.py          person.py
aliquot.py        forth.ipynb       myfile.txt        third.ipynb
fibs.py           forth_ready.ipynb myfunc.py


In [145]:
pop = pd.read_csv("/Users/qiwsir/Documents/Codes/DataSet/gdppop/gdp-population.csv")
pop

City_Name       GDP  Population
0   SHANGHAI  27466.15     2419.70
1    BEIJING  24899.30     2172.90
2  GUANGZHOU  19610.90     1350.11
3   SHENZHEN  19492.60     1137.87
4    TIANJIN  17885.39     1562.12
5  CHONGQING  17558.76     3016.55
6     SUZHOU  15475.09     1375.00
7    CHENGDU  12170.20     1591.76

In [146]:
pd.read_csv?