# Jupyter的基本应用方法

In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.2'

In [3]:
#数组
lst = ['a', 1, [1,2,3]]
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [4]:
type(data)

numpy.ndarray

In [7]:
data.dtype

dtype('int64')

In [8]:
data.astype(np.float)

array([1., 2., 3., 4., 5.])

In [9]:
data

array([1, 2, 3, 4, 5])

In [10]:
data.dtype

dtype('int64')

In [11]:
data.astype?

In [12]:
data.shape

(5,)

In [13]:
data

array([1, 2, 3, 4, 5])

In [14]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
c.shape

(2, 3)

In [16]:
c.ndim

2

In [17]:
c.size

6

In [18]:
np.array?

In [20]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [21]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones((4,))

array([1., 1., 1., 1.])

In [23]:
np.ones(4)

array([1., 1., 1., 1.])

In [24]:
data

array([1, 2, 3, 4, 5])

In [26]:
a = np.array([[1,2,3],[3,4,5]])
np.ones(a.shape)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.ones_like(a, dtype=np.float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
8 * np.ones((2,3))

array([[8., 8., 8.],
       [8., 8., 8.]])

In [31]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.diag([1,2,3,4], k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [34]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [35]:
np.logspace(1, 3, num=4)

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [39]:
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [40]:
b = np.linspace(0, 100, 5)
b

array([  0.,  25.,  50.,  75., 100.])

In [41]:
b[3]

75.0

In [43]:
c = np.logspace(1, 3, 12).reshape(3,4)
c

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [  53.36699231,   81.11308308,  123.28467394,  187.38174229],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [44]:
c.shape

(3, 4)

In [48]:
c[0, 1]

15.199110829529339

In [46]:
c[1]

array([ 53.36699231,  81.11308308, 123.28467394, 187.38174229])

根据索引获取某一个元素，下标
data[m, n, p, ...]

In [49]:
b

array([  0.,  25.,  50.,  75., 100.])

In [50]:
b[0], b[2], b[3]

(0.0, 50.0, 75.0)

In [51]:
#获取一个数组中多个元素，列表中是元素索引
# b.shape--->(5,)
b[[0, 2, 3]]

array([ 0., 50., 75.])

In [52]:
c

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [  53.36699231,   81.11308308,  123.28467394,  187.38174229],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [53]:
c[[0, 2]]  #0轴方向的两个元素

array([[  10.        ,   15.19911083,   23.101297  ,   35.11191734],
       [ 284.80358684,  432.87612811,  657.93322466, 1000.        ]])

In [55]:
c[np.array([0, 2]), [1, 2]]

array([ 15.19911083, 657.93322466])

从数组中获取多个值
data[[m,n,p], [m,n,p],...]

In [56]:
b

array([  0.,  25.,  50.,  75., 100.])

In [57]:
for i in b:
    if i == 50:
        print(i)

50.0


In [59]:
t = b == 50
t

array([False, False,  True, False, False])

In [60]:
b[t]

array([50.])

In [61]:
e = np.arange(10).reshape(2,5)
t = e % 2 == 0
e[t]

array([0, 2, 4, 6, 8])

In [62]:
e

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
t2 = np.array([False, True])
e[t2]

array([[5, 6, 7, 8, 9]])

# 数组的切片

In [64]:
a = np.arange(10, 20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [67]:
b = a[2: 8]
b

array([12, 13, 14, 15, 16, 17])

In [68]:
b[0] = 1200
b

array([1200,   13,   14,   15,   16,   17])

In [69]:
a

array([  10,   11, 1200,   13,   14,   15,   16,   17,   18,   19])

In [70]:
a[::2]

array([  10, 1200,   14,   16,   18])

In [71]:
b = np.arange(0, 60, 10).reshape(-1, 1) + np.arange(0, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [78]:
np.arange(0, 6)

array([0, 1, 2, 3, 4, 5])

In [77]:
np.arange(0, 60, 10).reshape(-1, 1)

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [72]:
b[1:4]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [73]:
b[1:4, 2:5]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])